import { HugeiconsIcon } from "@hugeicons/react";
import type { IconSvgElement } from "@hugeicons/react";
import * as H from "@hugeicons/core-free-icons";
import type { ComponentType, SVGProps } from "react";

export type IconProps = Partial<SVGProps<SVGSVGElement>> & {
  size?: number | string;
  strokeWidth?: number;
};

export type LucideIcon = ComponentType<IconProps>;

function createIcon(icon: IconSvgElement): LucideIcon {
  return function Icon({ size, strokeWidth, ...props }: IconProps) {
    return <HugeiconsIcon icon={icon} size={size} strokeWidth={strokeWidth} {...props} />;
  };
}

export const Menu = createIcon(H.Menu01Icon);
export const X = createIcon(H.Cancel01Icon);
export const ChevronDown = createIcon(H.ChevronDownIcon);
export const ChevronRight = createIcon(H.ChevronRightIcon);
export const ChevronLeft = createIcon(H.ChevronLeftIcon);
export const ArrowRight = createIcon(H.ArrowRightIcon);
export const ArrowLeft = createIcon(H.ArrowLeftIcon);
export const ArrowUpRight = createIcon(H.ArrowUpRightIcon);
export const Copy = createIcon(H.Copy01Icon);
export const Check = createIcon(H.CheckIcon);
export const CopyCheck = createIcon(H.CopyCheckIcon);
export const CheckCircle2 = createIcon(H.CheckmarkCircle01Icon);
export const Sun = createIcon(H.Sun01Icon);
export const Moon = createIcon(H.Moon01Icon);
export const Loader2 = createIcon(H.LoadingIcon);
export const LifeBuoy = createIcon(H.LifebuoyIcon);
export const BookUser = createIcon(H.BookUserIcon);
export const Library = createIcon(H.LibraryIcon);
export const FolderKanban = createIcon(H.FolderKanbanIcon);
export const BarChart3 = createIcon(H.ChartColumnIcon);
export const Cpu = createIcon(H.CpuIcon);
export const Settings = createIcon(H.Settings01Icon);
export const LogOut = createIcon(H.Logout01Icon);
export const LayoutGrid = createIcon(H.LayoutGridIcon);
export const Code2 = createIcon(H.CodeXmlIcon);
export const TerminalSquare = createIcon(H.TerminalIcon);
export const Bot = createIcon(H.BotIcon);
export const Brain = createIcon(H.BrainIcon);
export const History = createIcon(H.HistoryIcon);
export const Search = createIcon(H.Search01Icon);
export const KeyRound = createIcon(H.Key01Icon);
export const DollarSign = createIcon(H.DollarSignIcon);
export const PiggyBank = createIcon(H.PiggyBankIcon);
export const Briefcase = createIcon(H.BriefcaseIcon);
export const GraduationCap = createIcon(H.GraduationCapIcon);
export const Users = createIcon(H.UserGroupIcon);
export const Shuffle = createIcon(H.ShuffleIcon);
export const Wand2 = createIcon(H.MagicWand01Icon);
export const Sparkles = createIcon(H.SparklesIcon);
export const Scissors = createIcon(H.Scissor01Icon);
export const Wallet = createIcon(H.Wallet01Icon);
export const FileDown = createIcon(H.FileDownIcon);
export const Hammer = createIcon(H.HammerIcon);
export const CircleDashed = createIcon(H.CircleDashedIcon);
export const Star = createIcon(H.StarIcon);
export const Play = createIcon(H.PlayIcon);
export const Shrink = createIcon(H.ShrinkDotIcon);
export const ClipboardList = createIcon(H.ClipboardListIcon);
export const ClipboardPaste = createIcon(H.ClipboardPasteIcon);
export const MessageSquareWarning = createIcon(H.MessageCancel01Icon);
export const Timer = createIcon(H.TimerIcon);
export const Minus = createIcon(H.MinusSignIcon);
export const Mail = createIcon(H.MailIcon);
export const Lock = createIcon(H.LockIcon);
export const Clock = createIcon(H.Clock01Icon);
export const ArrowDown = createIcon(H.ArrowDown02Icon);
export const ArrowUp = createIcon(H.ArrowUpIcon);
export const User = createIcon(H.UserIcon);
export const Eye = createIcon(H.EyeIcon);
export const EyeOff = createIcon(H.EyeOffIcon);
export const TrendingUp = createIcon(H.ChartUpIcon);
export const TrendingDown = createIcon(H.ChartDownIcon);
export const Plus = createIcon(H.PlusSignIcon);
export const AiChat = createIcon(H.AiChat01Icon);
export const Save = createIcon(H.SaveIcon);
export const Bookmark = createIcon(H.BookmarkIcon);
export const AlertTriangle = createIcon(H.Alert02Icon);
export const Trash2 = createIcon(H.Delete01Icon);
export const Layers = createIcon(H.LayersIcon);
export const ShieldCheck = createIcon(H.Shield01Icon);
export const Shield = createIcon(H.Shield01Icon);
export const Send = createIcon(H.Forward01Icon);
export const Gauge = createIcon(H.GaugeIcon);
export const Bell = createIcon(H.BellIcon);
export const Palette = createIcon(H.ColorsIcon);
export const CreditCard = createIcon(H.CreditCardIcon);
export const Pencil = createIcon(H.PencilIcon);
export const Archive = createIcon(H.Archive01Icon);
export const Refresh = createIcon(H.GlobalRefreshIcon);
export const MoreHorizontal = createIcon(H.MoreHorizontalIcon);
export const More = createIcon(H.MoreIcon);
export const FileCode2 = createIcon(H.FileCodeIcon);
export const Zap = createIcon(H.ZapIcon);
export const Award = createIcon(H.AwardIcon);
export const Pin = createIcon(H.PinIcon);
export const BookmarkPlus = createIcon(H.BookmarkAddIcon);
export const Folder = createIcon(H.FolderIcon);
export const GitBranch = createIcon(H.GitBranchIcon);
export const Globe = createIcon(H.GlobeIcon);
export const Terminal = createIcon(H.TerminalIcon);
export const Quote = createIcon(H.QuoteUpIcon);
export const Github = createIcon(H.GithubIcon);
